### PR TITLE
Fix #31, fix #28: correct verbalization of slowdown/speed up

### LINKED ISSUE #28: When running benchmarks against a baseline, it is unclear whether the baseline was compared against
https://github.com/Bodigrim/tasty-bench/blob/7de1e2a78c33f186279121dc68eca52c16831f5c/src/Test/Tasty/Bench.hs#L1724

The above line shows that when the change in runtime against the baseline is essentially 0, then no indication is given. The first output is a typical slowdown:

```
      41.7 ms ± 3.7 ms, 157 MB allocated,  19 MB copied,  14 MB peak memory, 97203242% slower than baseline
```

but the thing is that when running against a baseline, I want to see in words "unchanged against baseline". Not seeing that text makes it confusing as to whether the baseline was even tested against. Here is an example:

```
      41.7 ms ± 3.7 ms, 157 MB allocated,  19 MB copied,  14 MB peak memory
```

This is confusing to at least myself and my coworker. What do you think?

By the way - thanks for the awesome library!

### LINKED ISSUE #31: Misleadling verbalization of speed up / slow down
I was surprised that a
1. "75% faster than baseline" (see https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8072#note_427599)
2. was advertised as "4 times faster" (see https://github.com/haskell/core-libraries-committee/issues/59#issue-1227722396)

75% faster means 1.75 times as fast, so, which one is true?  Turns out "4 times faster" is (sort of) true, but the verbalization of the speed up is incorrect:
https://github.com/Bodigrim/tasty-bench/blob/fc8f806cbd4596aba61cfc58e356b2075eaa64f0/src/Test/Tasty/Bench.hs#L1763-L1770
(In this code `n` is the fraction _new duration divided by old duration_.)

The verb "faster" is about comparison of velocities.  So if run 5 km/h and you 10 km/h, you run
_5 km/h faster_ than me.  Relativising this to the baseline of my speed, you run _100% faster_ than me.  Much easier to understand is the sentence _you run 2 times as fast as me_ (where proper English would be "twice as fast").

This bug is another proof that people are just terrible when it comes to percentage calculations.

I suggest to avoid percentage calculation and also comparative adjectives (which require you to subtract the baseline).  Rather, __just print the factor__.  So,  instead of 
> 75% faster than baseline

print:
> 4.0 times as fast as the baseline

### PR DESCRIPTION
**Pull request by andreasabel**
Fixes 
- #31 
- #28 

Follows suggestion raised towards
- #29 (superseded)

New output (example):
```
  insert
    Set Bool: OK (1.80s)
      845  ns ±  63 ns, unchanged against baseline
    BoolSet:  OK (2.34s)
      138  ns ± 7.2 ns, faster than baseline by factor 6.13
```

### CODE REVIEW

**Comment by Bodigrim** [comment]
Superseded by fce531307fd58f2b94f81ce4c8445c693fae070b

**Comment by andreasabel** [comment]
LGTM, except for missing acknowledgement in commit, e.g. "jww Andreas Abel" or "with contributions by ..." etc.
Citations, acknowledgements and the like are the currency in science and volunteer work.
Next time...

**Comment by Bodigrim** [comment]
@andreasabel sorry, I appreciate our discussion in #28 a lot and it __is__ cited in the commit message. In terms of actual implementation fce531307fd58f2b94f81ce4c8445c693fae070b does not bear much resemblance to 003ad47 or 51ca6ce, and I did not read them beforehand.

**Comment by andreasabel** [comment]
> ... and I did not read them beforehand.

That doesn't make it better, haha!
Anyway, not a big thing...

**Pull request closed without merging**
